after_success: yarn run coveralls

before_install:
  - nvm install 8
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn add -g lerna@3.4.0

branches:
  except:
  - wedeploy

cache:
  yarn: true

install:
  - yarn

jdk:
  - oraclejdk8

language: java

script:
  - yarn run checkFormat
  - yarn run lint
  - yarn run test